### ISSUE TITLE
No color for numbered list in Markdown

### ISSUE THREAD

**Issue by linhtto** [edheltzel/vscode-better-solarized#1]
Thanks for the theme, it's really nice!

One thing I notice compared to the default: The default highlights the numbered list items different from the main text, which can be very helpful. An example:

```markdown
1. Group 1

   We discuss group 1 here.

2. Group 2

   Here we discuss group 2.
```
The default highlights the titles "1. Group1" and "2. Group 2" in Yellow, and the paragraphs in white. Currently,  Better Solarized Dark has everything as the regular paragraph color.

I'm not really sure how to customize this, but I hope you can update the theme to add this feature. Thanks!

**Comment by edheltzel** [comment]
what file type are you seeing that? Assuming markdown?

**Comment by linhtto** [comment]
Yes it's markdown. Sorry I only mentioned that in the title.

**Comment by linhtto** [comment]
I just want to add a note that the default dark theme (Dark +) highlights the numbers ("1." and "2.") similar to how it appears above with Github markdown. The titles "Group 1" and "Group 2" themselves are the same color as the main text. For the default Solarized Dark theme, the whole numbered list titles are highlighted in Yellow.

Better Solarized currently has everything including the numbers as the main-text color.

Please let me know if you can replicate this and can modify the theme. Thank you!
