### ISSUE TITLE
Feature: Add support for Semantic Highlighting

### ISSUE THREAD

**Issue by jonasbb** [edheltzel/vscode-better-solarized#14]
The Semantic Highlighting API allows the language server to provide much better syntax highlighting. I want to ask if this is a feature you want to support in this theme.

Here is an overview about [Semantic Highlighting](https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview).

**Comment by edheltzel** [comment]
I'll take a gander at it
