### ISSUE TITLE
Idea: use different colors for string delimiters and escape sequences

### ISSUE THREAD

**Issue by andronocean** [edheltzel/vscode-better-solarized#15]
Hey — firstly, thank you for creating this theme. It's really well done! I've been happily using it for a couple weeks, and this is the first time I've found something that annoys me.

Right now, the color scheme used to highlight escape sequences is the same as what's used for highlighting quotation marks at the start and end of strings. So, if I'm escaping quote marks within a string, it _looks_ like it's the end of the string at a glance, unless I look closely.

Here's a PHP example (though it's the same in JS):

<img width="659" alt="better-solarized-escapes" src="https://user-images.githubusercontent.com/26490481/110704849-8b439500-81c3-11eb-9311-6208c732201f.png">

By comparison, here's how another theme (Monokai Pro) handles the same escapes:

<img width="659" alt="monokai-pro-escape-coloring" src="https://user-images.githubusercontent.com/26490481/110705025-c8a82280-81c3-11eb-8df4-ba921ba7861a.png">

It's a little thing, but this would be a lovely detail to include.

**Comment by edheltzel** [comment]
Let me see what I can do - I actually do use this theme as my daily driver. 

I'm always open to PRs.

**Comment by edheltzel** [comment]
@andronocean here is a preview of the update:

Better Selenized Dark:
![better-selenized-dark](https://github.com/edheltzel/vscode-better-solarized/assets/402910/80a6df90-4890-48cd-a465-033622b03a85)

Better Solarized Dark (italic is the same):
![better-solarized-dark](https://github.com/edheltzel/vscode-better-solarized/assets/402910/251072fc-1ac4-4fed-a939-c8dcb956b8e3)

**Comment by andronocean** [comment]
Oh that's awesome! A belated thank you for this.
