### ISSUE TITLE
lua code:  parameters are too light

### ISSUE THREAD

**Issue by nankedr** [edheltzel/vscode-better-solarized#17]
![image](https://user-images.githubusercontent.com/11912288/166919148-7634b348-cb7a-405f-8789-05f0c5144cd0.png)

Parameter “msg" above is too light，I don't know how to change it  (LOL)

**Comment by edheltzel** [comment]
@nankedr I can't seem to reproduce your highlighting issue... do you have any other extensions that might be causing it? 

My test was just creating a new file setting the grammar to Lua and copied your example, but I disabled all extensions just to make sure I didn't have anything extra making highlights.
![image](https://user-images.githubusercontent.com/402910/167023081-c7af5354-360e-4c7d-a776-cc2c955627c3.png)

**I don't write Lua, sorry if I'm missing something** 🤷‍♂️

**Comment by nankedr** [comment]
> @nankedr I can't seem to reproduce your highlighting issue... do you have any other extensions that might be causing it?
> 
> My test was just creating a new file setting the grammar to Lua and copied your example, but I disabled all extensions just to make sure I didn't have anything extra making highlights. ![image](https://user-images.githubusercontent.com/402910/167023081-c7af5354-360e-4c7d-a776-cc2c955627c3.png)
> 
> **I don't write Lua, sorry if I'm missing something** 🤷‍♂️

WOW,  you're right. I find out the reason, indeed  another extension is causing it.   thanks!
