### ISSUE TITLE
Selected text in Jupyter Notebooks is not highlighted

### ISSUE THREAD

**Issue by ritog** [edheltzel/vscode-better-solarized#18]
Selected text in Jupyter Notebooks is not highlighted, and I am clueless about which text I selected.

Steps to reproduce:

- Open a jupyter notebook
- create a code cell
- type in some code
- select some code either with Shift + arrow keys or mouse

You will see that selected text is not highlighted.

___

### 🟩 Expected behavior (from a [different theme](https://github.com/bbrakenhoff/vscode-solarized-custom))

![Kazam_screencast_00000_V1](https://github.com/edheltzel/vscode-better-solarized/assets/58001482/63299ed6-5450-46b8-8715-f5495f000cab)

(selected text gets highlighted)

### ⚠️ Actual behavior (this theme)

![Kazam_screencast_00000_V4](https://github.com/edheltzel/vscode-better-solarized/assets/58001482/7a7c82d3-39b5-4482-8cd5-23d1a11eeda3)

(selected text **doesn't** get highlighted)

____

```
Version: 1.82.2
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:51:20.981Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.4.6-76060406-generic
```

**Comment by edheltzel** [comment]
That's kind of a bummer... I'll have to figure this out since I do not personally use Python and when I created the theme there was no support for Jupyter notebooks, so i expect there might be a few theme properties that do not work as expected.

**Comment by ritog** [comment]
I never developed themes for vs code before. But can you point to some things where I might dig?

I linked to a different theme where it works.

Do you have any rough ideas why that theme works, and it doesn't?

Please don't mind these questions because I have actually no idea how themes in code editors work.

**Comment by edheltzel** [comment]
@ritog I just published an update.

**Comment by ritog** [comment]
@edheltzel thanks!



I see the newest one in GH is **0.9.7**, but in Visual Studio marketplace it is still **0.9.6**. I think the update takes time, (assuming it is automatic). 🙂

![image](https://github.com/edheltzel/vscode-better-solarized/assets/58001482/c05f8c02-27e8-4e4d-8a24-6d17760baf94)

Let's see if this fixes the problem.

**Comment by ritog** [comment]
@edheltzel 

I get this error now when I try to set the theme. Is this because something is wrong on my end or yours?

> Unable to load file:///home/*[REDACTEDUNAME]*/.vscode/extensions/ginfuru.ginfuru-better-solarized-dark-theme-0.9.7/themes/Better%20Solarized%20Light-color-theme.json: Problems parsing JSON theme file: Comma expected, Comma expected, Value expected, Comma expected, Value expected

NOTE: I have downloaded **0.9.7** now, and restarted and all that.

**Comment by edheltzel** [comment]
> @edheltzel thanks!
> 
> 
> 
> I see the newest one in GH is **0.9.7**, but in Visual Studio marketplace it is still **0.9.6**. I think the update takes time, (assuming it is automatic). 🙂
> 
> ![image](https://github.com/edheltzel/vscode-better-solarized/assets/58001482/c05f8c02-27e8-4e4d-8a24-6d17760baf94)
> 
> Let's see if this fixes the problem. 
> 
> 
> 

I'm at a Jiu-Jitsu tournament, I see the issue and will address it. If you go the extension, download 0.9.6

**Comment by ritog** [comment]
@edheltzel 

Enjoy your Jiu-Jitsu tournament, Ed.

I actually really like your theme and care about it, that's why took the time to raise this issue, and want this theme to be flawless.

I now have the **0.9.7** and the new issue is [this](https://github.com/edheltzel/vscode-better-solarized/issues/18#issuecomment-1741787508):

> @edheltzel
> 
> I get this error now when I try to set the theme. Is this because something is wrong on my end or yours?
> 
> > Unable to load file:///home/_[REDACTEDUNAME]_/.vscode/extensions/ginfuru.ginfuru-better-solarized-dark-theme-0.9.7/themes/Better%20Solarized%20Light-color-theme.json: Problems parsing JSON theme file: Comma expected, Comma expected, Value expected, Comma expected, Value expected
> 
> NOTE: I have downloaded **0.9.7** now, and restarted and all that.

**Comment by ritog** [comment]
The issue is **FIXED** for both Better Solarized Dark, and Better Solarized Dark Italics. Selected text is now highlighted as expected.


![image](https://github.com/edheltzel/vscode-better-solarized/assets/58001482/bc10e327-98e9-41c6-a171-4e36e3e9b117)


I am creating a new issue mentioning the Light theme as there is a bug for the light theme only.
