### ISSUE TITLE
Syntax highlight support for Markdown

### ISSUE THREAD

**Issue by ianyepan** [edheltzel/vscode-better-solarized#2]
The syntax highlight for Markdown files (.md) is rather weak, I had to switch to the VSCode default solarized dark theme (which has surprisingly good at markdown syntax highlight) whenever I edit a markdown file.
For other filetypes, I really love your theme!!
Keep it up, just wish it could be even more perfect!

**Comment by edheltzel** [comment]
@ianpan870102 Other than #1 what is weak about it... ? Just need to try and figure out what you're expecting, I'm guessing you're wanting better `inline-code`, list highlighting? 


#### Here is my comparison:
https://i.makitra.in/2NejlPG

**Comment by ianyepan** [comment]
Dear ginfuru,

Thank you for the email!
I hope that the attached two screenshots can successfully elaborate the
syntax highlighting differences in VSCode-solarized-dark, and your
Better-Solarized dark (which seems to be quite 'grayed-out' in 80% of my
Markdown code).

Best,
Ian

Ed Heltzel <notifications@github.com> 於 2018年9月13日 週四 下午8:34寫道：

**Comment by linhtto** [comment]
@ianpan870102, would you mind showing the screenshots as part of the post? Attaching them to the email probably doesn't work.

**Comment by ianyepan** [comment]
Sure, I'll try to include the photo of comparison here again. On the left side is the original VSCode solarized-dark, on the right is the theme of yours. Most sections seem to be grayed out.
 
<img width="1440" alt="screenshot 2018-10-02 at 10 20 18" src="https://user-images.githubusercontent.com/36686900/46325910-1ac8df00-c62d-11e8-9569-52f539167dbb.png">

**Comment by edheltzel** [comment]
@ianpan870102 
What version of the ther theme are you using? 

Also you're showing blockquotes mainly in your `md` file so I'm not sure what the issue here is.

**Comment by ianyepan** [comment]
I'm using the latest version that comes with the VSCode built-in themes. Yes, I am showing the '.md' code -- not the preview -- because I'm discussing the syntax highlight.

**Comment by linhtto** [comment]
This screenshot is great. I can see now that even for the main text, the font color is a shade darker than in other types of files.

I like the beige color much more than the orange one by VSCode, but it's a shade too dark.

**Comment by edheltzel** [comment]
This is what `blockquotes` looks like with Dank Mono 
![screen shot 2018-10-02 at 1 03 40 pm](https://user-images.githubusercontent.com/402910/46364372-9b92d580-c643-11e8-8eb3-b8a0fe19a5bb.png)
