### ISSUE TITLE
Selected text is very low contrast in light theme

### ISSUE THREAD

**Issue by jojanzing** [edheltzel/vscode-better-solarized#21]
Great implementation of the solarized theme, thank you!

Only one issue: selected text highlight is almost invisible while in the light theme, as the highlight colour barely differs from the background colour. In dark theme, selected text highlights as expected.

**Comment by edheltzel** [comment]
@jojanzing, could you send me a screenshot of the issue?

**Comment by pintergreg** [comment]
![Képernyőkép_20240415_150731](https://github.com/edheltzel/vscode-better-solarized/assets/3854784/86a32f7e-ce85-43b8-9061-71084fe25f71)

The pivot_table part is selected, which is indicated only by the visible white spaces. It is practically unusable for me in this way.

edit: I forgot to tell, that this happens only in a Jupyter notebook environment.

```
Version: 1.88.0
Commit: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c
Date: 2024-04-05T09:25:05.142Z
Electron: 28.3.0
ElectronBuildId: undefined
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.8.5-arch1-1
```

**Comment by pintergreg** [comment]
Could be fixed using customization:

```json
"workbench.colorCustomizations":{
  "notebook.editorBackground": "#eae0c0",
  "notebook.cellEditorBackground": "#fdf6e3"
},
```
![Képernyőkép_20240416_115306](https://github.com/edheltzel/vscode-better-solarized/assets/3854784/9ba1d40a-0ab9-4973-8a4e-e7e587e87b79)

**Comment by edheltzel** [comment]
Awesome, I can push this through a little later today or you're welcome to create a PR
