### ISSUE TITLE
Consider supporting 🌔 "Selenized" 🌒 theme

### ISSUE THREAD

**Issue by santoso-wijaya** [edheltzel/vscode-better-solarized#22]
Would you consider adding support for Selenized theme? Kinda like this nvim [solarized palette](https://github.com/maxmx03/solarized.nvim/blob/main/lua/solarized/palette.lua)?

What if I take a stab at it?

**Comment by edheltzel** [comment]
@santoso-wijaya I'll have to look into it. Not sure what Selenized is, but looks interesting from what I found and seems like there is already development for [vscode](https://github.com/jan-warchol/selenized/tree/master/editors/visual-studio-code)

**Comment by santoso-wijaya** [comment]
It does, but it also seems stalled (last update ~4y ago). The colorscheme itself is complete. I've been testing it on my nvim and terminals and I really like the marginal improvements it makes over Solarized (especially the red-magenta-orange separation).

And since it's based on Solarized, I think you can make it a "theme" of an existing Solarized plugin such as this, rather than a whole separate colorscheme/plugin. Just as the author of [`solarized.nvim`](https://github.com/maxmx03/solarized.nvim/blob/main/lua/solarized/palette.lua) had done.

I've already been using this vscode solarized plugin for a while now, and I enjoy it. I think it would be nice for this plugin to offer "Selenized" variants, as well.

**Comment by edheltzel** [comment]
Yeah I didn't even look at the last commit date. 

I'll probably just add it in as an option, for both the light and dark versions.
