### ISSUE TITLE
Text that matches currently selected text has very low contrast on light theme

### ISSUE THREAD

**Issue by williamangelo** [edheltzel/vscode-better-solarized#24]
First issue here, been a user of the extension for a while now, awesome job!

Very similar issue as stated in https://github.com/edheltzel/vscode-better-solarized/issues/21, in light theme the contrast in any text that matches the currently highlighted text is barely visible.

Same text in both themes, examples from a .sql file
![image](https://github.com/edheltzel/vscode-better-solarized/assets/39243586/063641fd-15c1-407a-a6c2-d36d428042b6)
![image](https://github.com/edheltzel/vscode-better-solarized/assets/39243586/bf4619c5-660a-41b9-86da-235b263e09d2)

**Comment by edheltzel** [comment]
@williamangelo - **are you using a Jupyter notebook?**

**Comment by williamangelo** [comment]
No! This is directly in VSCode
