### ISSUE TITLE
Correction to markdown list coloring

### ISSUE THREAD

**Issue by linhtto** [edheltzel/vscode-better-solarized#3]
This is a follow-up to https://github.com/ginfuru/vscode-better-solarized-dark/issues/1.

Thanks for the update!

I think there's a small typo:
`punctuation.definition.list.begin.markdown` should actually be `beginning.punctuation.definition.list.markdown`. Right now there's no effect.

**Comment by edheltzel** [comment]
I'll take a peek at it... If you think you've got a fix `PRs` welcome and encouraged

**Comment by linhtto** [comment]
Unfortunately I have no experience. I was just guessing after noticing that it doesn't work for me, and looking at the scope name. But it seems to show up fine in the screenshot in #2 (the blue `-` for unordered list) so I'm not sure. For me there's still no coloring for either numbered or unordered lists.

**Comment by edheltzel** [comment]
@linhtto No worries

**This is what I have for lists inside of Markdown:**
![screen shot 2018-10-02 at 11 45 48 am](https://user-images.githubusercontent.com/402910/46360368-3e922200-c639-11e8-96a7-17436b61248d.png)
