### ISSUE TITLE
New bracket colors do not match the themes (Solarized Dark)

### ISSUE THREAD

**Issue by sarpuser** [edheltzel/vscode-better-solarized#30]
Hello,

The new bracket colors added to solarized dark as of commit [15ff6e59924a7e6a3072fc23d6693f5f4a3159e6](https://github.com/edheltzel/vscode-better-solarized/commit/15ff6e59924a7e6a3072fc23d6693f5f4a3159e6) (5/10/24) are very different to the theme and in my opinion do not match at all. It is very disorienting to see all the whiteish brackets. I personally think these colors should either be changed back to the defaults or more closely aligned to the rest of the theme. If that is not possible, would you be able to provide me with the bracket color scheme that VSCode uses by default for other dark themes? It doesn't seem to be listed in any of the theme files on the VSCode GitHub. 

Thanks

**Comment by edheltzel** [comment]
Can you take a screenshot and share it?

**Comment by sarpuser** [comment]
New:
<img width="444" alt="Screenshot 2024-05-16 at 13 06 04" src="https://github.com/edheltzel/vscode-better-solarized/assets/23362324/4fea26c1-1927-44c3-8045-77b2ce6b1b90"> <br>
 vs Old (default in VSCode for dark themes, I think):
<img width="420" alt="Screenshot 2024-05-16 at 13 06 18" src="https://github.com/edheltzel/vscode-better-solarized/assets/23362324/d7f5b112-6371-4ce6-8cd7-b558dd90737b">

**Comment by edheltzel** [comment]
@sarpuser Thanks for that - the workspace UI originally just used the default off-the-shelf colors from VSCode. I agree that the new colors do seem off or out of order, but the change does follow the current default Solarized Dark workbench UI theme. **I have no issues rolling those back or at least updating them to be more consistent.**

in the meantime here are the default colors:
```json
    "editorBracketHighlight.foreground1": "#FFD700",
    "editorBracketHighlight.foreground2": "#DA70D6",
    "editorBracketHighlight.foreground3": "#179fff",
```

**Comment by sarpuser** [comment]
I appreciate the quick response! Thank you for being open to looking into this. I do not know what colors the brackets should be to better fit the theme, but personally I think the default values look pretty good. I'll leave that decision to you.

**Comment by edheltzel** [comment]
@sarpuser would you mind trying these settings for Solarized Dark? 
```json
      "editorBracketHighlight.foreground1": "#B58900",
      "editorBracketHighlight.foreground2": "#D33682",
      "editorBracketHighlight.foreground3": "#268BD2",
      "editorBracketHighlight.foreground4": "#644EA0",
      "editorBracketHighlight.foreground5": "#2AA198",
      "editorBracketHighlight.foreground6": "#CB4B16",
      "editorBracketHighlight.unexpectedBracket.foreground": "#D30102",
      "editorBracketMatch.border": "#657B83A0",
      "editorBracketPairGuide.activeBackground1": "#B58900",
      "editorBracketPairGuide.activeBackground2": "#D33682",
      "editorBracketPairGuide.activeBackground3": "#268BD2",
      "editorBracketPairGuide.activeBackground4": "#644EA0",
      "editorBracketPairGuide.activeBackground5": "#2AA198",
      "editorBracketPairGuide.activeBackground6": "#CB4B16",
  ```
