### ISSUE TITLE
Illegible terminal text

### ISSUE THREAD

**Issue by scottinet** [edheltzel/vscode-better-solarized#31]
Hi!

I was trying this theme, and I like it, except it has the same problem as the default Solarized Dark theme: some texts in the VSCode terminal are illegible due to their color being the same as the background one.

Here are a few screenshot to illustrate:

**Better Solarized Dark**

![image](https://github.com/edheltzel/vscode-better-solarized/assets/12997967/f28b5424-29a1-4f48-84b5-60eeb2e1d202)

**Better Selenized Dark (ok)**

![image](https://github.com/edheltzel/vscode-better-solarized/assets/12997967/749fdcfc-97d9-40e5-b734-3a5e924b0084)

**(for reference) Solarized Dark (default VSCode theme)**

![image](https://github.com/edheltzel/vscode-better-solarized/assets/12997967/6e2ac9af-cf24-4d36-9d2e-f7e351b15b5e)

**Comment by edheltzel** [comment]
Thanks for catching this.

**Comment by scottinet** [comment]
Theming is not my forte (at all) so I won't submit a PR for this issue, but just in case, the culprit is `terminal.ansiBlack` which has the same value in both the `Better Solarized Dark` and `Better Solarized Dark Italic` themes than the terminal background color.

I forced it to a color I handpicked (randomly, sorry, I'm bad at this), near the background color, using this configuration:

```json
  "workbench.colorCustomizations": {
    "terminal.ansiBrightBlack": "#454a4c"
  }
```

![image](https://github.com/edheltzel/vscode-better-solarized/assets/12997967/bea06e02-238e-47af-ae80-588a55b47dda)

**Comment by edheltzel** [comment]
Appreciate it... I've fixed the values. I'll include this in the next release.
