### ISSUE TITLE
Better Solarized Light – red sidebar issue

### ISSUE THREAD

**Issue by RDMCz** [edheltzel/vscode-better-solarized#33]
![obrazek](https://github.com/edheltzel/vscode-better-solarized/assets/9787182/6eb06132-26b5-4b00-9105-195c8d24e922)

**Comment by RDMCz** [comment]
This happened after last update.

I am using it mainly for writing Markdown and it looks like the color for unordered list bullets (asterisk or hyphen) and ordered list numbers was also changed. It's blue now, I think it was more red-ish :D

**Comment by edheltzel** [comment]
I see the issue, I'll make an update here shortly. 

~~Could you send me what you're seeing for markdown?~~

~~Also wanna make sure you're talking about the activity bar being red with your original screen shot?~~

**Comment by edheltzel** [comment]
@RDMCz Give a few minutes and check for extension updates and then reload the window. 

Thanks for catching the typo

**Comment by RDMCz** [comment]
Thank you for very quick response, the main issue is gone now.

I was talking about these: 
![MD](https://github.com/edheltzel/vscode-better-solarized/assets/9787182/2f3e7e1b-b98d-4f14-acbc-837de4145f07)

They were definitely different color, I think the same as `#` in the heading (?). But I can live with that :)

**Comment by edheltzel** [comment]
@RDMCz  awesome
