### ISSUE TITLE
Gray background color on tabs in dark mode

### ISSUE THREAD

**Issue by JulindM** [edheltzel/vscode-better-solarized#34]
Somehow after the last update I am getting this weird (what looks to be like) default grey background color on the tabs when in dark mode.
![Screenshot 2024-05-27 at 17 34 52](https://github.com/edheltzel/vscode-better-solarized/assets/11739524/54fc531e-ce1b-45a3-92fd-08ede8f9efb0)

---
Here is a portion of my `settings.json` related to tabs if it helps you in any way. 
```json
  "workbench.editor.tabSizingFixedMaxWidth": 100,
  "workbench.editor.tabSizingFixedMinWidth": 100,
  "workbench.editor.pinnedTabsOnSeparateRow": true,
  "workbench.editor.wrapTabs": true,
  "workbench.editor.showTabs": "multiple",
  "workbench.editor.pinnedTabSizing": "shrink",
  "workbench.editor.tabSizing": "shrink",
```

Edit: This seems to happen only on the `Better Solarized Dark` version of the theme. `Better Selenized Dark` does not have this bug.

**Comment by edheltzel** [comment]
@JulindM I'll have this fixed locally, just haven't pushed a release yet. 
In the mean time:
```json
"editorGroupHeader.tabsbackground": "#004454";
```
