### ISSUE TITLE
Inline hints should be better contrasted against the background

### ISSUE THREAD

**Issue by carlocaione** [edheltzel/vscode-better-solarized#36]
Currently the inline hints are very poorly contrasted against the background:

<img width="686" alt="Screenshot 2024-06-19 at 13 58 09" src="https://github.com/edheltzel/vscode-better-solarized/assets/357758/80c9e87c-7cd2-4a9e-9320-fd5a47a1cd12">

so sometimes it is really hard to say what it the actual code and what are the hints generated by VS.

Maybe it is even possible to set some kind of transparency for the hints to suggest that those are not actual code?

**Comment by edheltzel** [comment]
Hmm, are your hints coming from Copilot?
