### ISSUE TITLE
Jupyter cells are white

### ISSUE THREAD

**Issue by oscu0** [edheltzel/vscode-better-solarized#37]
<img width="1624" alt="Screenshot 2024-07-26 at 14 22 59" src="https://github.com/user-attachments/assets/f4ed5559-f0b3-4afb-bafd-f3bbc0962fc7">
When using the untamed workbench (which is something I've wanted for a very long time), Jupyter code cells are also turned white. Hopefully this isn't because they use the sidebar color or something hardcoded like that.

**Comment by edheltzel** [comment]
@oscu0 Are you using `Better Solarized` them?  I guess I'm not familiar with your "untamed workbench"?

**Comment by oscu0** [comment]
Unthemed workbench from a different theme. 
I've opened this in the wrong theme's repo after browsing several, sorry.

**Comment by edheltzel** [comment]
> Unthemed workbench from a different theme. 
> I've opened this in the wrong theme's repo after browsing several, sorry.

No worries
