### ISSUE TITLE
Colors of quotes in Markdown

### ISSUE THREAD

**Issue by linhtto** [edheltzel/vscode-better-solarized#4]
I'm not sure if this is what @ianpan870102 has in mind for Markdown https://github.com/ginfuru/vscode-better-solarized-dark/issues/2, but the color of a quoted block is quite dark.

**Comment by edheltzel** [comment]
No screen shot attached.

**Comment by linhtto** [comment]
The screenshot in #2 should explain it.

Quoted blocks are the lines that start with ">".

**Comment by edheltzel** [comment]
Hmm - I'm not sure that I agree with this request... I get that the blockquote has `>` The reason it’s a more muted color is because it is also italic -- having it all the same color and matching the default Solarized Dark defeats the purpose?

**Comment by edheltzel** [comment]
I think the best route would be to add a `Bright` version of the color scheme to accommodate the request...?
