### ISSUE TITLE
disable italics

### ISSUE THREAD

**Issue by zwhitchcox** [edheltzel/vscode-better-solarized#8]
I really like this theme, but there's no way to disable the italics, and I can't really read the code very well in italics

**Comment by edheltzel** [comment]
I can respect that,  Let me slice out sometime in my schedule to see what I can do to add a variant.

**Comment by zwhitchcox** [comment]
Thanks! By the way, I actually forked your theme, and the only thing I changed was the variable italics, because I found that a bit distracting, but everything else is good, at least for me.

[I went ahead and published the extension just so I could easily get to it in the future](https://marketplace.visualstudio.com/items?itemName=zwhitchcox.zwhitchcox-better-solarized-dark-theme), so, if you just want to link to that, that's cool, or if you get the variant, I'll just take it off the market place.

**Comment by edheltzel** [comment]
Fixed with #10
